/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MotocycleManage;

import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author phu ngu
 */
public final class SaleForm extends javax.swing.JFrame {

    /**
     * Creates new form SaleForm
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private User user;

    public SaleForm(User u) {
        initComponents();
        user = new User(u);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        con = new db().mycon();
        if (con == null) {
            JOptionPane.showMessageDialog(null, "fb not available");
        }
       
        txtprice.setEnabled(false);
        txtCusAddress.setEnabled(false);
        txtCustomerEmail.setEnabled(false);
        area.setEditable(false);
        btGen.setEnabled(false);
        btPrint.setEnabled(false);
        btDel.setEnabled(false);
        btPay.setEnabled(false);

        getdatacustomer();
        jComboBox1.removeAllItems();
        bindCombobox();
        showTableData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cb_color = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMoneytook = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbChange = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtCusPhone = new javax.swing.JTextField();
        btDel = new javax.swing.JButton();
        btPay = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        btGen = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtCustomerEmail = new javax.swing.JLabel();
        txtCusAddress = new javax.swing.JLabel();
        lbAcnn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Bike Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 39, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Date ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 93, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Price");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtprice.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpricePropertyChange(evt);
            }
        });
        jPanel2.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 153, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Amount");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });
        jPanel2.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 153, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 36, 147, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Color");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        cb_color.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_color.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_colorItemStateChanged(evt);
            }
        });
        cb_color.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_colorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_colorFocusLost(evt);
            }
        });
        cb_color.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_colorPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_colorPopupMenuWillBecomeVisible(evt);
            }
        });
        cb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_colorActionPerformed(evt);
            }
        });
        jPanel2.add(cb_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 104, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Total : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 335, -1, -1));

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 332, 210, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Money took");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 335, -1, -1));

        txtMoneytook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMoneytook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMoneytookKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoneytookKeyTyped(evt);
            }
        });
        jPanel2.add(txtMoneytook, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 332, 230, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Change :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 335, -1, -1));

        lbChange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lbChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 332, 190, 28));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Customer Name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 153, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Customer Email");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Address");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MotocycleManage/Reset20.png"))); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Phone");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtCusPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCusPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCusPhoneKeyReleased(evt);
            }
        });
        jPanel2.add(txtCusPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, 30));

        btDel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete20.png"))); // NOI18N
        btDel.setText("Delete ");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });
        jPanel2.add(btDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 60));

        btPay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay20.png"))); // NOI18N
        btPay.setText("PAY");
        btPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPayActionPerformed(evt);
            }
        });
        jPanel2.add(btPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 110, 60));

        btPrint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print20.png"))); // NOI18N
        btPrint.setText("Print bills");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 150, 60));

        btGen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill20.png"))); // NOI18N
        btGen.setText("Generate reciept");
        btGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenActionPerformed(evt);
            }
        });
        jPanel2.add(btGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 180, 60));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 82, 145, 33));
        jPanel2.add(txtCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 150, 22));

        txtCusAddress.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtCusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 150, 50));

        lbAcnn.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbAcnn.setForeground(new java.awt.Color(255, 0, 51));
        lbAcnn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbAcnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 124, 153, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Sale");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BikeID", "Bike Name", "Color", "Price", "Date", "Amount", "Total", "Money Take", "Change", "Customer Name", "Customer Email", "Phone", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        area.setColumns(20);
        area.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back20.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(636, 636, 636)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    public void showTableData() {

        try {

            pst = con.prepareStatement("Select * from sale order by BikeName");
            rs = pst.executeQuery();

            ResultSetMetaData stdata = rs.getMetaData();
            int q = stdata.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();

            while (rs.next()) {
                Vector columdata = new Vector();
                int i;
                for (i = 1; i < q; i++) {
                    columdata.add(rs.getInt("id"));
                    columdata.add(rs.getString("BikeName"));
                    columdata.add(rs.getString("Color"));
                    columdata.add(rs.getString("Price"));
                    columdata.add(rs.getString("Date"));
                    columdata.add(rs.getString("Amount"));
                    columdata.add(rs.getString("Total"));
                    columdata.add(rs.getString("Took"));
                    columdata.add(rs.getString("ChangeMoney"));
                    columdata.add(rs.getString("CustomerName"));
                    columdata.add(rs.getString("CustomerEmail"));
                    columdata.add(rs.getString("Phone"));
                    columdata.add(rs.getString("Address"));
                }
                RecordTable.addRow(columdata);

            }

        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "cant show");
        }
    }

    public void bindCombobox() {
        jComboBox1.removeAllItems();
        String sql = "Select * from bikeinfo ";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {

                int amount = rs.getInt("Amount");
                if (amount <= 0) {
                    System.out.println("" + amount);
                    continue;
                }
                String bikename = rs.getString("BikeName");
                this.jComboBox1.addItem(bikename);

            }

        } catch (Exception e) {
            System.err.println("e");
        }
    }

    public void binditem() {
        txtprice.removeAll();
        try {

            String sql = "Select * from bikeinfo where BikeName= '" + jComboBox1.getSelectedItem().toString() + "' AND Color= '" + cb_color.getSelectedItem().toString() + "' ";
            pst = con.prepareStatement(sql);

            rs = pst.executeQuery();
            while (rs.next()) {
                String price = rs.getString("Price");
                this.txtprice.setText(price);
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void bindColor() {
        cb_color.removeAllItems();
        try {
            String sql = "Select * from bikeinfo where BikeName= '" + jComboBox1.getSelectedItem() + "' ";
            pst = con.prepareStatement(sql);
            System.out.println("" + jComboBox1.getSelectedItem());

            rs = pst.executeQuery();

            while (rs.next()) {

                String color = rs.getString("Color");
                this.cb_color.addItem(color);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void getdatacustomer() {

        try {
            String sql = "SELECT * FROM customerinfo where CustomerName='" + txtCustomerName.getText() + "' AND Phone='" + this.txtCusPhone.getText().trim() + "'";
            pst = con.prepareStatement(sql);

            rs = pst.executeQuery(sql);
            while (rs.next()) {

                String email = rs.getString("Email").trim();
                String Add = rs.getString("Address").trim();
                this.txtCustomerEmail.setText(email);
                this.txtCusAddress.setText(Add);
            }
        } catch (Exception e) {
        }
    }

    void check() {
        if (txtAmount.getText().equals("") || txtCustomerName.getText().equals("") || txtCusPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Plese Enter enough information", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPayActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String date = sdf.format(this.jDateChooser1.getDate());

        try {
            
            check();
            String sql = "INSERT INTO sale(BikeName,Color,Price,Date,Amount,Total,Took,ChangeMoney,CustomerName,CustomerEmail,Phone,Address) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);

            pst.setString(1, jComboBox1.getSelectedItem().toString());
            pst.setString(2, cb_color.getSelectedItem().toString());
            pst.setString(3, txtprice.getText());
            pst.setString(4, date);
            pst.setString(5, txtAmount.getText());
            String totalmoney = lbTotal.getText().replace("đ", "VND");
            pst.setString(6, totalmoney);
            System.out.println(lbTotal.getText());
            pst.setString(7, txtMoneytook.getText().replace("đ", "VND"));
            pst.setString(8, lbChange.getText());
            pst.setString(9, txtCustomerName.getText());
            pst.setString(10, txtCustomerEmail.getText());
            pst.setString(11, txtCusPhone.getText());
            pst.setString(12, txtCusAddress.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sussess !!! ");

            pst = con.prepareStatement("UPDATE bikeinfo SET Amount = Amount - '" + txtAmount.getText().trim() + "' where BikeName ='" + jComboBox1.getSelectedItem() + "' AND Color='" + cb_color.getSelectedItem() + "'");
            pst.executeUpdate();
            updateTable();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btPayActionPerformed

    void updateTable() {
        try {
            pst = con.prepareStatement("SELECT * FROM sale");
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        int selectRows = jTable1.getSelectedRow();
        try {
            int id = (int) RecordTable.getValueAt(selectRows, 0);
            int deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete ?", "Warning", JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION) {
                pst = con.prepareStatement("DELETE FROM sale WHERE id=?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Deleted");

                txtprice.setText("");

                txtAmount.setText("");
                txtCustomerName.setText("");
                txtCusPhone.setText("");
                txtCustomerEmail.setText("");
                txtCusAddress.setText("");
                updateTable();

            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_btDelActionPerformed

  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.user.getUser_Name().equals("admin")) {
            this.dispose();
            Home home = new Home(user);
            home.setVisible(true);
        } else {
            HomeEmploy home = new HomeEmploy(user);
            this.dispose();
            home.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:      
      
        txtprice.removeAll();
        bindColor();
        binditem();

    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void txtpricePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpricePropertyChange
        // TODO add your handling code here:


    }//GEN-LAST:event_txtpricePropertyChange

    private void cb_colorPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_colorPopupMenuWillBecomeInvisible
        // TODO add your handling code here:


    }//GEN-LAST:event_cb_colorPopupMenuWillBecomeInvisible

    private void txtCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyReleased
        // TODO add your handling code here:
        getdatacustomer();
    }//GEN-LAST:event_txtCustomerNameKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JDateChooser choose = new JDateChooser();
        choose.setCalendar(null);

        txtCusAddress.setText("");
        txtCustomerEmail.setText("");
        txtCustomerName.setText("");
        jDateChooser1.setCalendar(null);
        txtCusPhone.setText("");
        txtprice.setText("");
        txtAmount.setText("");
        lbTotal.setText("");
        lbChange.setText("");
        txtMoneytook.setText("");
        cb_color.setSelectedIndex(-1);
        jComboBox1.setSelectedIndex(-1);
        txtMoneytook.setEnabled(true);
        btPay.setEnabled(false);
        btDel.setEnabled(false);
        btGen.setEnabled(false);
        btPrint.setEnabled(false);
        updateTable();
        area.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCusPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusPhoneKeyReleased
        // TODO add your handling code here:
        getdatacustomer();
    }//GEN-LAST:event_txtCusPhoneKeyReleased

    public static String formatMoney(double money) {
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
        return currencyVN.format(money);
    }

    public static boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public static double formatStringToMoney(String money) {
        String r = money.replace("VND", "").replace(".", "").replace(" ", "");
        if (isNumeric(r)) {
            return Double.parseDouble(r);
        }
        return -1000;
    }
    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        try {

            int amount = Integer.parseInt(txtAmount.getText());
            String txtprice1 = (this.txtprice.getText()).replaceAll("\\.", "");
            System.out.println("" + this.txtprice.getText());
            System.out.println("" + txtprice1);
            double price = Double.parseDouble(txtprice1);
            double total = (double) price * amount;

            lbTotal.setText(formatMoney(total).replace("đ", "VND"));
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_txtAmountKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        try {

            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();

            int selectRows = jTable1.getSelectedRow();

            jComboBox1.setSelectedItem(RecordTable.getValueAt(selectRows, 1).toString());
            cb_color.setSelectedItem(RecordTable.getValueAt(selectRows,2).toString().trim());
            txtprice.setText(RecordTable.getValueAt(selectRows, 3).toString());
            jDateChooser1.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String) RecordTable.getValueAt(selectRows, 4).toString()));
            txtAmount.setText(RecordTable.getValueAt(selectRows, 5).toString());
            lbTotal.setText(RecordTable.getValueAt(selectRows, 6).toString());
            txtMoneytook.setText(RecordTable.getValueAt(selectRows, 7).toString());
            lbChange.setText(RecordTable.getValueAt(selectRows, 8).toString());
            txtCustomerName.setText(RecordTable.getValueAt(selectRows, 9).toString());
            txtCustomerEmail.setText(RecordTable.getValueAt(selectRows, 10).toString());
            txtCusPhone.setText(RecordTable.getValueAt(selectRows, 11).toString());
            txtCusAddress.setText(RecordTable.getValueAt(selectRows, 12).toString());
            txtMoneytook.setEnabled(false);
            btGen.setEnabled(true);
            btPrint.setEnabled(true);
            btDel.setEnabled(true);
            btPay.setEnabled(false);

        } catch (ParseException ex) {
            Logger.getLogger(SaleForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void btGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenActionPerformed
        // TODO add your handling code here:

        area.setText("*******************************************\n");
        area.setText(area.getText() + "\t     *  Reciept  *\n");
        area.setText(area.getText() + "*******************************************\n");
        area.setText(area.getText() + " \t Motocycle store PBT \n");
        area.setText(area.getText() + " 475A Điện Biên Phủ, Phường 25, Bình Thạnh,\n\tThành phố Hồ Chí Minh  \n");

        Date obj = new Date();
        String date = obj.toString();
        area.setText(area.getText() + "\n" + date + "\n\n");
        area.setText(area.getText() + "Bike Name :\t\t" + this.jComboBox1.getSelectedItem().toString().trim() + "\n\n");
        area.setText(area.getText() + "Color :\t\t" + this.cb_color.getSelectedItem().toString().trim() + "\n\n");
        area.setText(area.getText() + "Price:\t\t" + this.txtprice.getText() + " VND \n\n");
        area.setText(area.getText() + "Amount:\t\t" + this.txtAmount.getText() + "\n\n");
        area.setText(area.getText() + "Customer Name:  \t" + this.txtCustomerName.getText() + "\n\n");
        area.setText(area.getText() + "Email:\t\t" + this.txtCustomerEmail.getText() + "\n\n");
        area.setText(area.getText() + "Phone: \t\t +84 " + this.txtCusPhone.getText() + "\n\n");
        area.setText(area.getText() + "Address:\t\t" + this.txtCusAddress.getText() + "\n\n");
        area.setText(area.getText() + "*******************************************\n");
        area.setText(area.getText() + "Total :\t\t" + this.lbTotal.getText() + "  \n\n");
        area.setText(area.getText() + "Take :\t\t" + this.txtMoneytook.getText() + "  \n\n");
        area.setText(area.getText() + "Change :\t\t" + this.lbChange.getText() + "  \n\n");
        area.setText(area.getText() + "*******************************************\n");
        area.setText(area.getText() + "*********Thank you for using services******\n");

    }//GEN-LAST:event_btGenActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        try {
            // TODO add your handling code here:
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(SaleForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPrintActionPerformed


    private void txtMoneytookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoneytookKeyReleased
        // TODO add your handling code here:
        try {

            double took = formatStringToMoney(this.txtMoneytook.getText());

            String txttotal = (this.lbTotal.getText()).replaceAll("\\.", "");
            System.out.println("" + this.lbTotal.getText());

            txtMoneytook.setText(formatMoney(took).replace("đ", "VND"));

            double a = formatStringToMoney(txttotal);
            double change = took - a;
            lbChange.setText(formatMoney(change).replace("đ", "VND"));

            btGen.setEnabled(true);
            btPrint.setEnabled(true);
            btPay.setEnabled(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtMoneytookKeyReleased

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            lbAcnn.setText("Only Number acept");
            evt.consume();
        } else {
            lbAcnn.setText("");
        }
    }//GEN-LAST:event_txtAmountKeyTyped

    private void cb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_colorActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cb_colorPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_colorPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        binditem();
        

    }//GEN-LAST:event_cb_colorPopupMenuWillBecomeVisible

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        cb_color.removeAllItems();
bindColor();
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1FocusGained

    private void txtMoneytookKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoneytookKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_txtMoneytookKeyTyped

    private void cb_colorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_colorFocusGained
        // TODO add your handling code here:

        bindColor();
    }//GEN-LAST:event_cb_colorFocusGained

    private void cb_colorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_colorItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_colorItemStateChanged

    private void cb_colorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_colorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_colorFocusLost

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            User user = new User();
            new SaleForm(user).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btGen;
    private javax.swing.JButton btPay;
    private javax.swing.JButton btPrint;
    private javax.swing.JComboBox<String> cb_color;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAcnn;
    private javax.swing.JLabel lbChange;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtCusAddress;
    private javax.swing.JTextField txtCusPhone;
    private javax.swing.JLabel txtCustomerEmail;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtMoneytook;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
